name: Upload artifact

on: workflow_dispatch

jobs:
  Upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - name: créer le fichier
      # commande linux pour créer un fichier
        run: echo "coucou toi <3" > artifact.txt
      - name: upload artifact
      # action qui permet de generer un artéfact
        uses: actions/upload-artifact@v3
        with:
        # nom que l'on souhaite donner à l'artefact
        # c'est ce nom qui apparaitre dans github
          name: Artifact
          # chemin de l'artéfact (dans le runner)
          path: artifact.txt

  # second job pour récupérer l'artifact produit par le 1er job
  download:
    name: Download
    # doit s'executer APRES le 1er job
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - name: download
      # action qui permet de dll un artifact dans un runner
        uses: actions/download-artifact@v3
        with:
        # on doit lui passer le nom qu'on a donné à l'artifact (L19)
          name: Artifact
      - name: Lire le fichier
      # on affiche le contenu du fichier avec 'cat'
        run: cat artifact.txt