name: exo_two_jobs

on: workflow_dispatch

jobs:
  exo_4:
    runs-on: ubuntu-latest
    steps: 
      - run : echo "Hello manu !"

  exo_4a:
    needs: [exo_4]
    runs-on: ubuntu-latest
    steps: 
      - run : echo "Hello auto !"