name: push or pull request

on: [push, pull_request]

env:
  PUSH: ceci est un push
  PULL_REQUEST: ceci est une pull request

jobs:
  whis_push:
    if: ${{github.event_name == 'push'}}
    runs-on: ubuntu-latest
    steps:
      - name: "c'est un push ?"
        run: echo "$PUSH"

  whis_pl:
    if: ${{github.event_name == 'pull_request'}}
    runs-on: ubuntu-latest
    steps:
      - name: "c'est une pull request ?"
        run: echo "$PULL_REQUEST"

